### ISSUE TITLE
number of classes error in accuracy plots

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#109]
When `affinity.csv` is not present, the accuracy_plot throws the following error:

`ValueError: The number of FixedLocator locations (13), usually from a call to set_ticks, does not match the number of labels (9).`

**Comment by crangelsmith** [comment]
This is also happening when by chance we don't get a class (e.g fidutial) in the train, test split and is expecting it in one of the figures. This is being fixed in the `evaluation` branch in PR #120.
