### ISSUE TITLE
Meta.pkl always need to be loaded in `evaluate.py`

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#126]
line 57 meta.pkl is read regardless of collect_meta being true. 

If this is moved to line 85, introduces an error as It is being used for the static embedding on line 100

**Comment by crangelsmith** [comment]
This should be fixed in [1445299](https://github.com/alan-turing-institute/affinity-vae/pull/120/commits/1445299eeb021ff0597978e5e72fad30f5d2bac5)
