### ISSUE TITLE
Dynamic exposure adjustment to make sure we can visualise the reconstructions. E.g:

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/affinity-vae#131]
We might have to do some dynamic exposure adjustment to make sure we can visualise the reconstructions. E.g:
Default: 
![trn_recon_out](https://github.com/alan-turing-institute/affinity-vae/assets/11162074/54c39334-4092-4d65-8940-bff65b47d939)
Exposure corrected:
![trn_recon_out](https://github.com/alan-turing-institute/affinity-vae/assets/11162074/d1f3f0c2-b22f-4390-8be9-ce8dc215e210)

_Originally posted by @crangelsmith in https://github.com/alan-turing-institute/affinity-vae/pull/127#discussion_r1217751170_

**Comment by jolaem** [comment]
Fixed by min-max normalisation
