### ISSUE TITLE
BandPass filter 

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#145]
Add band pass filter :

We can take the frequencies of the fat of the pristine molecule and then create a bandpass filter with frequencies obtained

**Comment by marjanfamili** [comment]
I have written the bandpass filter , however it is slow as it creates a filter for each datapoint. This may require refactoring of the data loader and data.py, so I will leave it for the moment being. The same filter can be applied to the data that is saved on the disk before we load the data

**Comment by crangelsmith** [comment]
This is now relevant for [caked](https://github.com/alan-turing-institute/caked/tree/main/src/caked), not affinity. Closing.
