### ISSUE TITLE
Logic on the command line arguments

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/affinity-vae#153]
There is some mismatch on the click command arguments between what is a flag and what takes arguments:

e.g: 

1. [Restart should be a flag?](https://github.com/alan-turing-institute/affinity-vae/blob/99047360bb0206361ea39803e159bb9855de95f4/run.py#L35)

2. [State should take an argument with the path to the state? Not be a flag](https://github.com/alan-turing-institute/affinity-vae/blob/99047360bb0206361ea39803e159bb9855de95f4/run.py#L42)

3. [Meta should take an argument with the path to the meta? Not be a flag](https://github.com/alan-turing-institute/affinity-vae/blob/99047360bb0206361ea39803e159bb9855de95f4/run.py#L50)

**Comment by marjanfamili** [comment]
yes
yes
yes

:D
