### ISSUE TITLE
Adding filters as an optional variable for the model. 

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#17]
Filters as well as number of channels and depth: 
Filters is a list with the length of depth of the network. 
The benefit of having filters as a variable is that the size of the filters can be random but not just a multiple of 2. 
If Filters was not present,  require the channel and depth parameters and construct filters from these parameters

**Comment by crangelsmith** [comment]
Do we want to have the filters also as an option in the yaml file? 

Can you provide a couple of examples of INPUT filters that should work here to test?

**Comment by jolaem** [comment]
I think they should have yaml entries, yes.

An example would be [8, 16, 34, 64].

**Comment by crangelsmith** [comment]
this has been implemented.
