### ISSUE TITLE
Bug when Freq_all is not specified

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#176]
Traceback (most recent call last):
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/run.py", line 703, in run
    train(
  File "/bask/projects/v/vjgo8416-ms-img-pc/marji/affinity-vae/avae/train.py", line 536, in train
    if config.VIS_CON and (epoch + 1) % config.FREQ_CON == 0:
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'

**Comment by marjanfamili** [comment]
I receive this error when the `Freq_all` flag is not specified. Im not sure when or where this was introduced

**Comment by crangelsmith** [comment]
> I receive this error when the `Freq_all` flag is not specified. Im not sure when or where this was introduced

I think this is because in the config Freq_all is defined by default as None, maybe we should change to False. However, I'm not sure why the error is complaining on FREQ_CON, that has a default definition, but maybe is not set up correctly?

**Comment by crangelsmith** [comment]
Somehow, freq_con gets set up as freq_all == None.

**Comment by marjanfamili** [comment]
Im not sure why it wouldn't be?  There is a default value of 10 in `config.py` for all of the frequencies. and my log file says that it is setup:

![image](https://github.com/alan-turing-institute/affinity-vae/assets/44607686/0e917848-56d8-44f5-8020-1e20ccb563ab)

**Comment by crangelsmith** [comment]
Found the bug :)

https://github.com/alan-turing-institute/affinity-vae/blob/8c673018d5e7551c72cfefb655ac721fd695a658/run.py#L680

**Comment by marjanfamili** [comment]
How did that get in there ??? :)). Thanks a lot. I fix it in my PR
