### ISSUE TITLE
Accept 2D inputs in models

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#18]
Refactor model_b to accept 2D inputs as model_a

**Comment by marjanfamili** [comment]
This is permitted in : 

https://github.com/alan-turing-institute/affinity-vae/blob/e2e2d9e743fdcf0a3e70ef5aae01c1cf03258de2/avae/model_a.py#L50


Where the type of convolution and convolution transpose layer is stored in conv and conv_T and passed to encoder and decoder accordingly

**Comment by crangelsmith** [comment]
this was implemented in PR #231
