### ISSUE TITLE
Create input file as an alternative option for flags 

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#19]
It is good to have an option for running the code with an input file. 
-  a sample of the input file can be uploaded and referenced in the ReadMe
- too many flags makes rerun more difficult
- input file can be used for various calculations with minor modification 

combine arguments received from command line to make it shorter or create a json file (input file) which contains all parametrs in clocked format (order of appearence should not affect)

**Comment by crangelsmith** [comment]
I'll start working on this one today.

**Comment by crangelsmith** [comment]
I'm testing this with a json file that will contain all the click options. Currently something like this (to be added affinity and classes path from PR #49) :

`
{
    "datapath": "data/shrec21_full_dataset/subtomo_files",
    "limit": 1000,
    "split": 20,
    "no_val_drop": true,
    "epochs":  10,
    "batch":  128,
    "depth":  3,
    "channels":  64,
    "latent_dims":  8,
    "pose_dims": 0,
    "beta":  1,
    "gamma":  2,
    "learning":  0.001,
    "loss_fn":  "MSE",
    "freq_eval": true,
    "freq_sta": true,
    "freq_emb": true,
    "freq_rec": true,
    "freq_int": true,
    "freq_dis": true,
    "freq_pos": true,
    "freq_acc": true,
    "freq_all": true,
    "vis_emb":  true,
    "vis_rec":  true,
    "vis_los":  true,
    "vis_int":  true,
    "vis_dis":  true,
    "vis_pos":  true,
    "vis_acc":  true,
    "vis_all":  true,
    "gpu":  true,
    "eval":  true,
    "dynamic": true
}
`

I remember there was a comment on Monday about using json for nested variables, so I wonder if @marjanfamili and @jolaem can advise where in these variables it would be useful to have nestedness (e.g. if vis_all and freq_all are true here then in the code all the related variables turn true, so is not really something that has to happen here)? Or maybe you were thinking about something else?

**Comment by crangelsmith** [comment]
> Hi Camila , this input file is still very difficult to read. Would it be possible to have the input file in a format that is easier to see?

I think this is due to using a json format, which is maximize for machine readability but probably not human one. We could use a `.py` config file (e.g see [this example](https://github.com/alan-turing-institute/monitoring-ecosystem-resilience/blob/master/pyveg/configs/config_all.py) from a previous project I worked on) but I thought there was an underlying reason to use json?

**Comment by jolaem** [comment]
So actually there is a config.py file already in the repo but it is very basic.

Regarding redability - we could simply format the json file better, no? Just realign all the brackets.

I think it would be good to preserve the `--freq_all` and `--vis_all` options to set all other params to true, they could be arg flags that change json parameters with a warning maybe?

Also would be good to have nesting to group different parameters together, but again we could do this easily wiht json files. Like Marjan said, categories like data, training, network, visualisation would work for me.

**Comment by marjanfamili** [comment]
Also we can have `.yaml` format  


# Input data parameters
data:
  train: /path/to/training/data
  test: /path/to/testing/data

# Model architecture parameters
model:
  type: lstm
  num_layers: 3
  hidden_size: 128

# Training parameters
training:
  num_epochs: 50
  batch_size: 32
  learning_rate: 0.001

**Comment by crangelsmith** [comment]
> Also we can have `.yaml` format . `PyYAML` library will read the file
> 
> # Input data parameters data: train: /path/to/training/data test: /path/to/testing/data
> 
> # Model architecture parameters model: type: lstm num_layers: 3 hidden_size: 128
> 
> # Training parameters training: num_epochs: 50 batch_size: 32 learning_rate: 0.001

Yes, this is perfectly fine as well!

**Comment by marjanfamili** [comment]
I find the Json still difficult to read , would the `config.py` allow comments as well ?

**Comment by crangelsmith** [comment]
Yes it would, but i think `.yaml` is probably best as is meant for exactly this kind of use.

**Comment by jolaem** [comment]
That sounds good to me!
