### ISSUE TITLE
Pose class disentanglement plot not working 

### ISSUE THREAD

**Issue by jolaem** [alan-turing-institute/affinity-vae#228]
The existing test for this had a typo and was not actually testing it. 

`143:        config.VIS_POSE_VIS = ["2", "5"]` - this variable doesn't control per-class pose visualisations, the variable should be called `VIS_POSE_CLASS` instead. Also this variable should be a comma separated string with no spaces as per help files: https://github.com/alan-turing-institute/affinity-vae/blob/12ad3d2e54b14cc791d4ff8529842436b3adca5f/run.py#L348

https://github.com/alan-turing-institute/affinity-vae/blob/12ad3d2e54b14cc791d4ff8529842436b3adca5f/tests/test_train_eval_pipeline.py#L143

The per-class pose visualisation trimmed the x set to class representatives but not the poses set which caused it to fail.

**Comment by marjanfamili** [comment]
Hi Jola, yes I have noticed this. It is a bug, Ive fixed it, just running tests now, will be pushing this in a few min. Thanks a lot

**Comment by jolaem** [comment]
Oh, right, I've also made a fix, was just about to push it

**Comment by marjanfamili** [comment]
oh , no problem. Please go ahead. Glad to know we have the same fix for the bug. Thanks
