### ISSUE TITLE
Tomogram Dataloader 

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#23]
We need a dataloader for tomograms that takes in the whole tomogram and saves subtomograms to the disk and loads them individually. 

Tomogram Dataloader :  
    - Read the tomogram in the dataloader init and create subtomograms save to disc and close. Then load from the saved files. (This essentially uns the script to save all the subtomograms)
    - For rotation which does not suffer from interpolation we can just flip n*90 degrees randomly in different directions. 
    - Pytorch tranform has in build rotation. We can try this for random rotation. 
    - Any rotation or transformation can be appended to transforms list in data.py. (Could create an extended class)

**Comment by crangelsmith** [comment]
This should be taken by [caked](https://github.com/alan-turing-institute/caked/tree/main/src/caked).
