### ISSUE TITLE
Config accepts parameters that do not exist

### ISSUE THREAD

**Issue by jolaem** [alan-turing-institute/affinity-vae#233]
We should check if a variable that doesn't exist has been entered into the config file. At the moment, typos are accepted silently as per below as a new parameters and a default for the corresponding parameter will be used. An error or at least a warning should be produced to warn user from using parameters that don't exist.

From `config/avae_final_config_***.yaml`

```
opt_method: adam
opt_metod: adam
```

**Comment by crangelsmith** [comment]
I think we should move our configuration to something like the one proposed in #201, this should help with parameter validation. It is on my to-do list for the next weeks whilst @jolaem  and @marjanfamili finalise experiments/manuscripts.

**Comment by crangelsmith** [comment]
This shoudnt happen anymore since we are using the pydantic model. Closing.
