### ISSUE TITLE
Affinity error in evaluation mode

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#274]
` logging.exception("An exception was thrown!", e)
Message: 'An exception was thrown!'
Arguments: (RuntimeError("Affinity matrix is needed to compute Affinity loss. Although you've set gamma, you have not provided --af/--affinity parameter."),)`

Should this error be produced in evaluation mode?

**Comment by crangelsmith** [comment]
I can't reproduce this error, it should have been fixed.
