### ISSUE TITLE
Set-up class inheritance for data loaders.

### ISSUE THREAD

**Issue by jolaem** [alan-turing-institute/affinity-vae#34]
Create an abstract data loader with most basic functionality:
- basic transforms (e.g. toTensor, unsqueeze);
- framework for loading affinity columns (if in train mode).

Ultimately this would allow people to create their own dataloaders for custom data.

Set up inheritance with other data loaders. Some ideas (2D > Abstract Image < 3D, 3D < Centered proteins < Full tomo with labels).

Rotatable dataloader should be simply submitted as an extension of non-rotatable with overwriting transforms in super.transforms.

This links with #23

**Comment by crangelsmith** [comment]
This is relevant to [caked](https://github.com/alan-turing-institute/caked/tree/main/src/caked) now, some are implemented, other parts evolved in different ways. Closing here.
