### ISSUE TITLE
plot affinity matrix for inspection

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#35]
It would be good to plot the affinity matrix in image format for inspections and comparisons

**Comment by marjanfamili** [comment]
![Image](https://user-images.githubusercontent.com/44607686/233634268-efb8762f-7e80-4a33-870d-387e818c54f0.png)

**Comment by marjanfamili** [comment]
The y labels are also highlighted now 


![Image](https://user-images.githubusercontent.com/44607686/233658837-58c8142e-076d-49d8-9f31-54e7a998eb30.png)

**Comment by jolaem** [comment]
This needs a patch as per #84
