### ISSUE TITLE
Fix the bug in the recent merge. the affinity matrix should be checked against all selected classes but not the ones existing in the dataset.

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#50]

**Comment by jolaem** [comment]
This should make sure to check against a whole dataset when no classes are passed.

**Comment by jolaem** [comment]
@marjanfamili as per @crangelsmith 's slack message I think you just need to move that block below the class check and replace the `ids` with the newly created attribute `self.final_classes`.
