### ISSUE TITLE
Remove hardcoded shape from model

### ISSUE THREAD

**Issue by quantumjot** [alan-turing-institute/affinity-vae#6]
https://github.com/alan-turing-institute/affinity-vae/blob/63e2483085f8bd13250f1e23aa2c6920fc524c95/affinivae/model.py#L57-L62

**Comment by marjanfamili** [comment]
Is it better if the convolution layers are done in a loop where we can define (receive) the depth of the network (number of conv layers ?)

**Comment by quantumjot** [comment]
> Is it better if the convolution layers are done in a loop where we can define (receive) the depth of the network (number of conv layers ?)

Yup - that would be ideal!
