### ISSUE TITLE
Summarise statistics of class representation on the dataset after limit cut

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/affinity-vae#67]
Summarise statistics of class representation on the dataset after the limit cut

Print values 
Plot histogram with classes

https://github.com/alan-turing-institute/affinity-vae/blob/df0e8f6239ce4963d34c0b94ff2f17d2011e2f0c/avae/data.py#L172

**Comment by jolaem** [comment]
I think this would be useful in general, not just with limit
