### ISSUE TITLE
Plot Cosmetics : Confusion matrix rotate labels at the bottom

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#76]

**Comment by marjanfamili** [comment]
![Image](https://user-images.githubusercontent.com/44607686/235157676-fe5f773a-baa4-466c-8092-7126cec4c57f.png)



![Image](https://user-images.githubusercontent.com/44607686/235157686-c6dc76c5-1b97-4b7f-bd7f-a7695f6cf97e.png)

**Comment by marjanfamili** [comment]
Are these better with bold font ?

**Comment by jolaem** [comment]
Think so! Looks good!

**Comment by jolaem** [comment]
![confusion_train](https://user-images.githubusercontent.com/6930946/235202270-e88f0beb-0289-4f97-8a4f-e61d4b3504e0.png)

This needs fixing so that values with more than 2 digits fit the box.

**Comment by marjanfamili** [comment]
Should be fixed
![confusion_train](https://user-images.githubusercontent.com/44607686/235629166-29b87d40-ffd9-41d3-adf4-993890da21d1.png)

**Comment by jolaem** [comment]
Testing on 54 classes from E.coli it is still unreadable. I think 54 should probs be our limit for now
![Screenshot from 2023-05-04 17-36-13](https://user-images.githubusercontent.com/6930946/236269523-052d2946-b17e-4dfc-9ac0-66a01fbc42d0.png)
