### ISSUE TITLE
Expose affinity matrix visualisation to command line and config

### ISSUE THREAD

**Issue by jolaem** [alan-turing-institute/affinity-vae#83]
The visualisation takes time. Allow for it to be optional (like all other visualisations) by exposing the flag to command line and config file.

**Comment by marjanfamili** [comment]
This particular visualisation only happens once and plotting a matrix that is already loaded. It should plot within less than couple of  seconds ?

**Comment by jolaem** [comment]
Yeah actually I had a cluster related issue that was slowing it down.

However still, I think it should have an option like all other visualisations (which also run fast, just prevents clogging up user directories with rubbish they don't need).
