### ISSUE TITLE
Cyclical Annealing Schedule: A Simple Approach to Mitigating KL Vanishing

### ISSUE THREAD

**Issue by marjanfamili** [alan-turing-institute/affinity-vae#88]
https://arxiv.org/abs/1903.10145

"Unfortunately, instability on text anal- ysis has been witnessed, in that the KL term LR becomes vanishingly small during training (Bow- man et al., 2015). This issue causes two undesir- able outcomes: (i) an encoder that produces poste- riors almost identical to the Gaussian prior, for all observations (rather than a more interesting pos- terior); and (ii) a decoder that completely ignores the latent variable z, and a learned model that re- duces to a simpler language model. This is known as the KL vanishing issue in text VAEs."

Implementing this , has improved the reconstructions 

[Cyc_vqvae.pptx](https://github.com/alan-turing-institute/affinity-vae/files/11396154/Cyc_vqvae.pptx)

**Comment by marjanfamili** [comment]
Cyclical Cosine 


![loss](https://user-images.githubusercontent.com/44607686/236168753-cdaf1d59-cbb1-455c-a4c9-a7768a7e45c4.png)
![trn_recon_in](https://user-images.githubusercontent.com/44607686/236168815-f1413985-4fcf-4e49-a06d-62a740501203.png)
![trn_recon_out](https://user-images.githubusercontent.com/44607686/236168819-a7342ec4-27ec-4021-a9e8-b7db2973da92.png)
![val_recon_in](https://user-images.githubusercontent.com/44607686/236168822-fbdc6ece-1a44-4c3b-a0f4-aa25cad3fe22.png)
![val_recon_out](https://user-images.githubusercontent.com/44607686/236168824-741401dc-6f3c-46ba-9076-7851297e0a42.png)

**Comment by marjanfamili** [comment]
Cyclical Linear 
![beta_array](https://user-images.githubusercontent.com/44607686/236169080-5afa17e1-d53b-429d-91af-e23172b850cf.png)

![loss](https://user-images.githubusercontent.com/44607686/236169021-b0f6cc33-e955-44e3-bd78-fa5416b41fb0.png)
![val_recon_in](https://user-images.githubusercontent.com/44607686/236169028-cd3f6eb9-1085-4388-9bce-c4ff6b30bcea.png)
![val_recon_out](https://user-images.githubusercontent.com/44607686/236169031-01ad4b77-0105-4f99-82f2-b2f860c2895a.png)

**Comment by marjanfamili** [comment]
![beta_array](https://user-images.githubusercontent.com/44607686/236169333-0e2d7613-1765-4f8b-9850-33714393b969.png)
![loss](https://user-images.githubusercontent.com/44607686/236169341-7919ee8f-f015-44db-999c-ebd79151b1ab.png)
![trn_recon_in](https://user-images.githubusercontent.com/44607686/236169344-175f5e21-9657-4d5a-99a1-c239068da92a.png)
![trn_recon_out](https://user-images.githubusercontent.com/44607686/236169346-d7486cc5-55b0-4caa-8d12-ae8963d11cb2.png)
![val_recon_in](https://user-images.githubusercontent.com/44607686/236169348-6bdf7159-9ac7-4a17-a403-f1eda4ed24df.png)
![val_recon_out](https://user-images.githubusercontent.com/44607686/236169351-b692313e-1111-4177-a5b9-5db6e3f381a5.png)

**Comment by jolaem** [comment]
Can you post some comparisons of latent spaces?

**Comment by marjanfamili** [comment]
There should be some in the presentation attached to the first comment
