### ISSUE TITLE
Update requirements to remove `pillow`

### ISSUE THREAD

**Issue by quantumjot** [alan-turing-institute/affinity-vae#9]
https://github.com/alan-turing-institute/affinity-vae/blob/63e2483085f8bd13250f1e23aa2c6920fc524c95/setup.cfg#L33

Remove `pillow`

**Comment by jolaem** [comment]
We now actually need Pillow for metadata gathering in dynamic plots, so closing this issue for now.

**Comment by jolaem** [comment]
We now actually need Pillow for metadata gathering in dynamic plots, so closing this issue for now.
