### ISSUE TITLE
Confusion matrix visualisation size for higher number of classes

### ISSUE THREAD

**Issue by jolaem** [alan-turing-institute/affinity-vae#91]
Confusion matrix visualisation fails when no `classes.csv` is present.

**Comment by marjanfamili** [comment]
![d](https://user-images.githubusercontent.com/44607686/236441930-4bcd96b7-3eb0-4765-a0b8-dcf79eb5ed20.png)
![confusion_train](https://user-images.githubusercontent.com/44607686/236441947-9b5a470c-9207-44ec-a186-293d6978f733.png)
![b](https://user-images.githubusercontent.com/44607686/236441979-dd75c83b-20b8-4737-ab57-7208075a2d8a.png)
![c](https://user-images.githubusercontent.com/44607686/236441992-ee0cbd7b-9de4-4716-8c09-67bd077012e8.png)
![e](https://user-images.githubusercontent.com/44607686/236442020-699ff530-b6b7-41fd-b5f0-e938ddc39617.png)

**Comment by jolaem** [comment]
Looks great! Label text is a bit small (not the actual labels, just the 'Predited label'), but this works for me now because I can see the actual results :)
